### ISSUE TITLE
Coap::Coap(UDP&) error

### ISSUE THREAD

**Issue by panzho** [hirotakaster/CoAP#4]
when i try to run the coaptest.ino on my arduino i get the next error 

libraries\CoAP-arduino\coap.cpp.o: In function `Coap::Coap(UDP&)':

C:\Program Files\Arduino\libraries\CoAP-arduino/coap.h:162: multiple definition of `Coap::Coap(UDP&)'

sketch\coap.cpp.o:sketch/coap.cpp:12: first defined here

libraries\CoAP-arduino\coap.cpp.o: In function `Coap::Coap(UDP&)':

C:\Program Files\Arduino\libraries\CoAP-arduino/coap.h:162: multiple definition of `Coap::Coap(UDP&)'

sketch\coap.cpp.o:sketch/coap.h:162: first defined here

libraries\CoAP-arduino\coap.cpp.o: In function `Coap::start(int)':
.
.
.
.
there are LOTS of more lines for this error but i think that this will be enough

**Comment by hirotakaster** [comment]
Do you install CoAP simple library from Arduino Library Manager or your-self from github?
Maybe your error message is caused by conflict of multiple library setting.
