### ISSUE TITLE
Error in Compiling from Particle Build

### ISSUE THREAD

**Issue by riansyahsumajaya** [hirotakaster/CoAP#6]
When i compile coapserver.ino in Particle Build, i got this message :

/workspace//src/coapserver.cpp:4:21: error: variable or field 'callback_light' declared void
                     ^
/workspace//src/coapserver.cpp:4:21: error: 'CoapPacket' was not declared in this scope
/workspace//src/coapserver.cpp:4:33: error: 'packet' was not declared in this scope
                                 ^
/workspace//src/coapserver.cpp:4:51: error: expected primary-expression before 'ip'
                                                   ^
/workspace//src/coapserver.cpp:4:55: error: expected primary-expression before 'int'
                                                       ^
/workspace//src/coapserver.cpp:7:24: error: variable or field 'callback_response' declared void
 void loop();
                        ^
/workspace//src/coapserver.cpp:7:24: error: 'CoapPacket' was not declared in this scope
/workspace//src/coapserver.cpp:7:36: error: 'packet' was not declared in this scope
 void loop();
                                    ^
/workspace//src/coapserver.cpp:7:54: error: expected primary-expression before 'ip'
 void loop();
                                                      ^
/workspace//src/coapserver.cpp:7:58: error: expected primary-expression before 'int'
 void loop();
                                                          ^
/workspace//src/coapserver.cpp:9:1: error: 'Coap' does not name a type
 void callback_light(CoapPacket &packet, IPAddress ip, int port);
 ^
/workspace//src/coapserver.cpp:13:21: error: variable or field 'callback_light' declared void
                     ^
/workspace//src/coapserver.cpp:13:21: error: 'CoapPacket' was not declared in this scope
/workspace//src/coapserver.cpp:13:33: error: 'packet' was not declared in this scope
                                 ^
/workspace//src/coapserver.cpp:13:51: error: expected primary-expression before 'ip'
                                                   ^
/workspace//src/coapserver.cpp:13:55: error: expected primary-expression before 'int'

Why can't i compile it? and what does that means?
Thanks

**Comment by b4k3r** [comment]
@hirotakaster, any thoughts?

**Comment by hirotakaster** [comment]
@b4k3r 
oh, I lost this issue. will update.

**Comment by hirotakaster** [comment]
now, update to 0.2.3.

**Comment by b4k3r** [comment]
@hirotakaster cool, thank you!
